### ISSUE TITLE
v1.0.0 - Multiple SQL data sources

### ISSUE THREAD

**Issue by GerilLeto** [merico-dev/table#20]
# Goals 

Configure and use multiple PG data sources in panels

# Tasks

- [x] @miguel-lansdorf Configure multiple PG connections in .env file. Note: name them uniquely
- [x] @miguel-lansdorf An API for getting connection list as available data sources
- [x] @GerilLeto Add **dataSources** to dashboard.definition, including these info
    1. type (Currently only **postgresql**)
    2. name (which db connection is being used to run query)
    3. query (query: { sql: string })
    4. id
- [x] @GerilLeto Change panel.sql to **panel.dataSourceID**, referencing **dashboard.definitions.dataSources**
- [x] @miguel-lansdorf Let `/query` API accepts **dataSource** as params instead of SQL
- [x] @GerilLeto Add a new config modal for editing **dashboard.definitions.dataSources**
- [x] @GerilLeto Change panel's **SQL** tab to **Data Source** tab
