### ISSUE TITLE
Dashboard CRUD API sample

### ISSUE THREAD

**Issue by GerilLeto** [merico-dev/table#4]
# Tasks
## Dashboard DB

- [x] SQLs for creating `a database` and `a table`
- [x] DB migration
- [x] a dump SQL for demo

1. use pg for database
2. following is an example of that table's structure

```SQL
CREATE TABLE
    "public"."dashboard" (
        "id" serial,
        "name" VARCHAR NOT NULL DEFAULT '',
        "content" jsonb NOT NULL DEFAULT '{}',
        "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
        "is_removed" bool NOT NULL DEFAULT 'false',
        PRIMARY KEY ("id")
    );
```

## Dashboard API
- [x] get dashboard list (name & id)
- [x] get dashboard detail
- [x] create dashboard
- [x] update dashboard
- [x] delete dashboard (set `is_removed` true)
